raviqqe/muffet

Dockerfile

Usage
```
$ docker build -t muffet .
$ docker run muffet -v https://coel-lang.org
```
This image can be pushed to Docker Hub by the maintainers.

#21 add Dockerfile

---

arguments.go
arguments_test.go
checker.go
checker_test.go
fetcher.go
fetcher_test.go
main.go
setup_test.go

Also a few other very minor changes.
All tests pass.
`go fmt`, `go vet`, `go lint` and [`megacheck`](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) has no complaints.
Example usage:
```
% ./muffet https://arodseth.com
https://arodseth.com
ERROR   https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib/1267524#1267524 (ID #1267524 not found)
ERROR   https://stackoverflow.com/questions/2951028/is-it-possible-to-include-inline-assembly-in-google-go-code/6535590#6535590 (ID #6535590 not found)
ERROR   https://unix.stackexchange.com/questions/82598/how-do-i-write-a-retry-logic-in-script-to-keep-retrying-to-run-it-upto-5-times/82610#82610 (ID #82610 not found)
```
(returns error code 1)
```
% ./muffet -i https://arodseth.com
```
(returns error …

Add an -i flag for ignoring the fragment part of URLs

---

arguments.go
arguments_test.go
checker.go
fetcher_option.go
main.go

I work on a large documentation site and find Muffet is an excellent tool, but I don't need to re-check the whole site when I'm changing a single page. This pull request adds a flag `--one-page-only` that checks all the links on the page, but doesn't follow the links and check what is on those pages. For our use case it would be great to only check the part we were working on most of the time, and then run the whole check periodically.

Add an option to check links on a single page only

---

arguments.go
arguments_test.go
checker_option.go
fetch_result_test.go
fetcher.go
fetcher_option.go
main.go
page.go
page_test.go
scraper.go
scraper_test.go

Many thanks for the Muffet tool, it gives me a quick and solid link check. However, in a RoR site I use URL parameters for pagination and I have noticed that URL parameters are truncated by default. Therefore, not all pages are checked. I've added the -u option, which then optionally causes URL parameters not to be truncated.

Adding option to follow URL parameters

---

go.mod
go.sum
main.go

When running muffet with Windows PowerShell or Command prompt, the colored log portion does not display properly.
*PowerShell on Windows 10 (1909)*
*Command prompt on Windows 10 (1909)*
I fixed it by using [go-colorable](https://github.com/mattn/go-colorable) to replace `os.Stdout`. Because this library returns `os.Stdout` as `io.Writer` for non-Windows systems, I think that this fix have no effect on the operation of other OSes.
*PowerShell on Windows 10 (1909)*
*Command prompt on Windows 10 (1909)*

fix an issue with the colored log in Windows shell.

---

fasthttp_http_client.go

One of our sites had a redirect location header that was broken (it was mostly correct but someone had removed the port number after the hostname and left the trailing colon).  This resulted in very confusing muffet output trying to track it down as the URL shown wasn't the redirect URL and the Atoi error sort of looked like a software bug.
strconv.Atoi: parsing "": invalid syntax	http://www.store.com/index.php?app=ecom&ns=prodshow&ref=33204
This minor change just wraps the error with some further context to make resolving the redirect issue quicker.

improve troubleshooting broken redirect URIs

---

arguments.go
arguments_test.go
command.go
fasthttp_http_client.go
fasthttp_http_client_factory.go
http_client_factory.go

There are 2 HTTP headers automatically set by muffet: User-Agent (through fasthttp) and Accept.
This PR disables adding those headers if they were provided by the user on the command line via the `--header` argument.

Disable default User-Agent and Accept headers if explicitly set by user

---

command.go
command_test.go
fake_http_response_test.go
fasthttp_http_client.go
fasthttp_http_client_factory.go
fasthttp_http_client_factory_test.go
http_client.go
http_client_factory.go
link_fetcher_test.go
page_checker_test.go
redirect_http_client.go
redirect_http_client_test.go
robots_txt_fetcher_test.go
sitemap_fetcher_test.go

Fix host throttling

---

.snapshots/TestHelp
arguments.go
arguments_test.go
command.go
fasthttp_http_client_factory.go
go.mod
go.sum
http_client_factory.go

Avoids overloading fasthttp and causing a panic.
I'm still trying to track down the specific URL that causes the problem so I can suggest a fix to fasthttp, but in the mean time it would probably be a good idea for muffet to avoid trying to read really huge pages.
Picked the default on the basis that the average page load these days is a few MB, and that includes resources such as images.

Add --max-response-body-size argument with default

---

link_finder.go

Fixes #211
Lightly tested, could use specific unit tests.

Match full URLs against include/exclude regexps

---

link_finder.go
link_finder_test.go

`<meta>` tags with specific `og:` and `twitter:` properties that map to URLs are now fetched.
Specific properties that are supported are:
- `og:image`
- `og:audio`
- `og:video`
- `og:image:url`
- `og:image:secure_url`
- `twitter:image`
Fixes #268

Support scraping opengraph/twitter meta tags

---

.snapshots/TestCommandFailWithJUnitAndJSONOptions
.snapshots/TestCommandFailWithVerboseAndJUnitOptions
.snapshots/TestHelp
.snapshots/TestMarshalErrorJSONPageResult
.snapshots/TestMarshalSuccessJSONPageResult
arguments.go
command.go
command_test.go
json_page_result.go
json_page_result_test.go
page_checker.go
page_result.go
page_result_formatter_test.go
page_result_test.go
xml_page_result.go

This PR does three things:
1. Allow including successful results in JSON output. (Fixes #214.)
2. Add JUnit output with a <kbd>--junit</kbd> flag. (Allows GitLab to parse output. Does not include skipped links.)
3. Track elapsed time for each link and each page. (Used in JUnit output.)
I’m not a Go developer, so let me know if there are any best practices or style guidelines I’ve ignored (most probably when updating existing tests to add durations with lots of repetition) and I’ll try to fix them. I modeled the JUnit addition after the existing JSON output and divided the changes into atomic commits as far as possible. There are no errors or warnings, the tests pass, and the JUnit output seems to be correct (I used [broken-links-inspector](https://github.com/dbogatov/broken-links-inspector …

Add JUnit output and expand JSON output

---

link_fetcher.go
link_fetcher_test.go

Ignore text fragments

---

arguments.go
arguments_test.go
command.go
fake_http_client_test.go
fasthttp_http_client.go
fasthttp_http_client_factory.go
http_client.go
http_client_factory.go
link_fetcher.go
redirect_http_client.go
redirect_http_client_test.go
robots_txt_fetcher.go
sitemap_fetcher.go
throttled_http_client.go

Fix #308.
Note that this logic is not perfect due to the current implementation of the standard `net/http/cookiejar` package which doesn't handle folded `set-cookie` headers properly. See also https://stackoverflow.com/questions/2880047/is-it-possible-to-set-more-than-one-cookie-with-a-single-set-cookie.

Handle cookies

---

sitemap_page_parser.go
sitemap_page_parser_test.go

Update `(*sitemapPageParser).Parse` to support both `application/xml` and `text/xml` as valid MIME types for sitemaps, previously only `application/xml` was considered valid.  However, popular HTTP servers such as Caddy (https://caddyserver.com) return a `Content-Type: text/xml; charset=utf-8` response header when serving a `sitemap.xml` sitemap file.  Currently, it is not possible to use `/sitemap.xml` as the root page with `muffet` when serving a site with an HTTP server such as Caddy due to `muffet` rejecting the `Content-Type` header and thus refusing to parse the site's sitemap file.
The official website for the sitemap protocol
(https://www.sitemaps.org) does not explictly state any specific `Content-Type` that should be used when serving sitemap files. However, the IANA's Media …

Allow application/xml and text/xml when parsing sitemaps

---

link_finder.go
link_finder_test.go

Close #345.
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

Fix data URLs with spaces

---

.snapshots/TestHelp
arguments.go
arguments_test.go
command.go
redirect_http_client.go
redirect_http_client_test.go
status_code_collection.go
status_code_collection_test.go
status_code_range.go
status_code_range_test.go

This pull request adds a new optional argument `--status-codes` to make the accepted HTTP response status codes configurable and solves #189 and #291.
I use muffet to check all links on https://tinylog.org/. However, some websites (e.g. https://stackoverflow.com, https://www.baeldung.com, and https://mkyong.com/) respond with status code 403 instead of 200 to muffet. Therefore, I would like to accept 403 as valid HTTP response status code.

Make accepted HTTP response status codes configurable

---

link_finder.go
link_finder_test.go

don't follow preconnect and dns-prefetch links

---

arguments.go

doc: document non-contiguous status code ranges

---

.github/workflows/release.yaml
tools/docker.sh

I saw this [issue](https://github.com/raviqqe/muffet/issues/413) and thought that it would be great for contributing to this project.
- Made some modifications to `docker.sh ` and to `release.yaml`
- Breaking changes: no

add different platforms for docker img

---

.snapshots/TestHelp
arguments.go
arguments_test.go
command.go
ignore_network_errors.go
page_checker.go
page_checker_test.go

The idea of the option is similar to `--accepted-status-codes=200..300,403,429,500..599`. It prevents false link check errors when some remote host is temporarily down or times out a request (often happens when there are lots of external links), but still allows checking for 404 when the remote host is functioning.
The default behavior is not to ignore these errors, as it was before. It's possible to either ignore all network errors, or to only ignore errors on external hosts.

Added --ignore-network-errors to optionally ignore network errors

---

.gitignore
.snapshots/TestHelp
arguments.go
arguments_test.go
command.go
link_fetcher.go
link_fetcher_options.go
page_checker.go
page_checker_test.go

Added `--retries` option to avoid false link check failures on site timeouts. By default it's 3 retries per url. Exponential delay starts at 500ms and doubles up to the cap of 5s.

Added `--retries` option
